apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserverdeployment
  labels:
    app: kubeserve
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
       - name: app
         image: leaddevops/kubeserve:v1
         ports:
         - containerPort: 80

